{
  imports = [
    #./deluge.nix
    #./discord.nix
    #./dragon.nix
    ./firefox.nix
    ./kitty.nix
    ./ghostty.nix
    ./obsidian.nix
    ./vlc.nix
    ./vivaldi.nix
    ./libreoffice.nix
    ./telegram.nix
    ./bottles.nix
    ./mpv.nix
    ./prismlauncher.nix
    ./motrix.nix
    ./obs.nix
    ./spotify.nix
    ./flameshot.nix

    ./cursor.nix
    ./vscode.nix
    ./zed.nix
    #./font.nix
    #./gtk.nix
    #./kdeconnect.nix
    #./pavucontrol.nix
    #./playerctl.nix
    #./qt.nix
    #./sublime-music.nix
  ];
}
